### PR TITLE
make `--config` a global option on `rita` command

### LINKED ISSUE #595: Move --config to a global option
So instead of having to do `rita import --config etc/rita.yaml ...` we would do `rita --config etc/rita.yaml import ...`. This makes it easier to modify most commands since `--config` is less likely to change than the rita subcommand. It also makes it possible to create aliases like:
- `alias rita1=rita --config /etc/rita/config1.yaml`
- `alias rita2=rita --config /etc/rita/config2.yaml`

Where currently this would be impossible with an alias and would need a custom shell function instead.

### PR DESCRIPTION
**Pull request by vivek-26**
This PR does the following:
  * makes `--config` a global option on the `rita` command.
  * removes `--config` flag from subcommands (`import`, `html-report` etc.)
  * uses [`GlobalString`](https://github.com/urfave/cli/blob/v1.22.0/flag_generated.go#L709) to fetch config value from global state. For reference, see this [issue](https://github.com/urfave/cli/issues/716).

Closes #595

### CODE REVIEW

**Comment by ethack** [comment]
This is great, thank you!

Do you think you could also migrate the `test-config` command to use the global option?
```
$ ./rita test-config --help                            
NAME:
   rita test-config - Check the configuration file for validity

USAGE:
   rita test-config [command options] [arguments...]

OPTIONS:
   --config value, -c value  specify a config file to be used
```

With these changes the config flag isn't recognized after the command. This invocation is what was needed prior to these changes and now produces an error. This could be a breaking change for some users. 
```
./rita show-beacons --config etc/rita.yaml test
Incorrect Usage: flag provided but not defined: -config
```

Do you know if there's a urlfave/cli option to have the `--config` flag recognized wherever it is placed? 

If there's not a simpler solution than putting the config flag back into all the subcommands and testing each case for both global and local config flags then I would rather we just announce the breaking change and possibly hold this until a major version bump. But if there's a clean fix that lets the flag be recognized anywhere then I'd be up for that to maintain backwards compatibility.

**Comment by vivek-26** [comment]
> Do you think you could also migrate the `test-config` command to use the global option?

Sure, will do that.


> Do you know if there's a urlfave/cli option to have the `--config` flag recognized wherever it is placed?

As per this [issue](https://github.com/urfave/cli/issues/585), there are 2 ways to achieve this. We could do something like [this](https://github.com/urfave/cli/issues/585#issuecomment-272987605) or we can upgrade `urfave/cli` to `v2`. I wrote a very simple example using `urfave/cli`-`v2` and global flag is recognised by all subcommands. However, upgrading `urfave/cli` to `v2` might cause breaking changes. ([example](https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flags-before-args))

**Comment by vivek-26** [comment]
@ethack I have updated PR to make `--config` flag available to both root command and all subcommands.

Current CLI behaviour is as follows - 
<hr>

Command: `$:  ./rita --config /etc/rita.yaml test-config`
Behaviour: `test-config` subcommand is aware of the `--config` flag value passed to the root command.
<hr>

Command: `$:  ./rita test-config --config /etc/rita.yaml`
Behaviour: `test-config` subcommand uses `--config` flag passed to it.
<hr>

Commands: 
`alias rita1=rita --config /etc/rita/config.yaml`
`$:  rita1 test-config --config /etc/new-config.yaml`

Behaviour: `test-config` subcommand overwrites `--config` value set globally  - `/etc/rita/config.yaml` and uses `/etc/new-config.yaml`.
<hr>

Closes #595

**Comment by vivek-26** [comment]
@ethack PTAL

**Review by ethack — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
