### PR TITLE
Fix the ports display on show scans

### PR DESCRIPTION
**Pull request by Zalgo2462**
Fix issue #207.

### CODE REVIEW

**Comment by Zalgo2462** [comment]
@ethack We discussed a possible performance issue regarding `rita show-scans -H -P [database]`. However, I looked through the library code we're using for the table writer, and there doesn't appear to be any faster way to create/ write the table. The AppendBulk method provided by the library, simply calls Append in a loop. 

However, I cannot reproduce the timings you had reported. Could you try another dataset and let me know your results?

**Comment by ethack** [comment]
I've confirmed this with a large dataset on the hunt server.  No `-H` returns in ~1s.  With `-H` I got tired of waiting and killed it after 2m15s.  Both times I piped output to /dev/null to avoid waiting for screen updates.  I confirmed the first command was returning results too by piping output to `head`.

```
$ time ./rita-fix show-scans --ports redacted > /dev/null

real	0m1.028s
user	0m1.116s
sys	0m0.044s
$ time ./rita-fix show-scans --ports -H redacted > /dev/null
^C
real	2m15.930s
user	2m14.664s
sys	0m1.680s
```

For comparison, here is the same test with the master branch rita.  Looks like this fix is an improvement in both speed and correctness for the CSV output at least!

```
$ time ./rita-master show-scans --ports redacted > /dev/null

real	0m20.510s
user	0m39.348s
sys	0m4.528s

$ time ./rita-master show-scans --ports -H redacted > /dev/null

real	0m21.160s
user	0m39.860s
sys	0m4.264s
```

**Comment by bekirk** [comment]
This fix was to address an issue I had is there something you want me to test or run?

I run my show-scans in a scheduled crontab so as long as it finishes by 7 am I don’t mind but that could be several hours since I start it at 1 am, last I checked all my tasks were completing around 4:30 am. But that hasn’t changed from pre Rita 1.0 till now. I can start recording time one it and see compare the results. I also don’t output it in human readable. I prefer csv.

**Comment by ethack** [comment]
@bekirk If you'd like to test out the proposed change and make sure it fixes the issue you were having that would be much appreciated.  Alternatively, you could just wait until we merge it into the master branch and let us know if you have any further issues after updating.

@Zalgo2462 I'm fine with the proposed pull request since it fixes the main issue, especially if there is nothing more to be done to improve the human readable processing time.  Actually, I'd be more inclined to want `--ports` and `-H` be mutually exclusive flags. 1) Because the processing time for building the table seems to be unreasonable and 2) because a gigantic list of ports on a single line kind of defeats the purpose of "human readable" anyway 😄 If that's an easy change feel free to make it.  And if not we can just merge it in as-is and count on folks not calling the two simultaneously.

**Comment by Zalgo2462** [comment]
@ethack I think its reasonable to make the flags mutually exclusive. I'll get right on that.

**Comment by Zalgo2462** [comment]
Let me know if you feel if it needs more documentation.

**Pull request merged**
